### ISSUE TITLE
problem with large number of preferences 

### ISSUE THREAD

**Issue by LoayAlshaddakh** [codders/dyad-finder#7] opened 2020-11-29 03:34 UTC
when i try to solve large number of preferences for example 1000 persons, i got this error :

Cannot read property 'preferences' of undefined
    at Mate6Service.calculate_next_loop_entry (mate6.service.ts:142)
    at Mate6Service.find_loop (mate6.service.ts:179)
    at Mate6Service.solve_for_stable (mate6.service.ts:216)
    at Mate6Service.solve (mate6.service.ts:281)

any hellp!

**Comment by codders** [comment] 2020-11-30 18:14
Hi @LoayAlshaddakh,

I guess from your stack trace that you are using the code in a different project - do you have a Github link for it?

It's hard to say what the error is without seeing the input data, but I would guess that one of the people in your dataset has expressed a preference for someone who doesn't appear in the dataset. Could that be possible? Can you share the dataset?

**Comment by LoayAlshaddakh** [comment] 2020-11-30 19:11
I am working on an ionic project that is about having input of n persons with their preferences such as the preference for age, language,nationally...etc

my app will then generate the prefrence list for each person in my system then it will pass it to your algorithm its hard to send the preference list because its of size
1000

your algorithm work perfectly with small number of persons such as 10, but I need to check original irving algorithm complexity time ( I assume you implement the original irving right?! )  with big number such as 3000,5000 and so on.Then compare the result with another algorithm that I suggest and it should be faster and better than the original one.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LoayAlshaddakh** [comment] 2020-11-30 19:14
I don't have the github for my project but I can send it to you.

and I don't think that someone willl have a person that is not in the system .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by codders** [comment] 2022-12-27 13:47
This appears to be a duplicate of #35 . I have reproduced the error using the dataset from @KeisukeNagakawa and resolved the issue.

**Closed as completed by codders** 2022-12-27 13:47 UTC
